[project]
name = "libotrank"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.5,<3.13"
tomli = ">=2.0.1,<2.1"
supabase = ">=2.6.0,<2.7"
python-dateutil = ">=2.9.0,<2.10"

[pypi-dependencies]
berserk = ">=0.13.2, <0.14"
